VERSION="2.2.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCYV5ZMRG32T6FCY4S3K636XFQSGKLKREWONR7UUGOBTJZG72BPXSEF5",
"GD53LHKFAKRWD5JKJJLPSYU6ARIHQYEOSH4UHHGONGDIBIY6QEFJTZWO"]

[DOCUMENTATION]
ORG_NAME="Astro Shiba Inu"
ORG_URL="https://www.astro-shiba.com/"
ORG_TWITTER="astroshibainu"



[[CURRENCIES]]
code="ASHIB"
issuer="GD53LHKFAKRWD5JKJJLPSYU6ARIHQYEOSH4UHHGONGDIBIY6QEFJTZWO"
display_decimals=7
name="Astro Shiba"
desc="Astro Shiba token on Stellar Network"
conditions="Astro Shiba (ASHIB) is token for fun. There are a total of 10,000,000,000 ASHIB the 50% of Astro Shiba will be burned over the course of 5 years, join the revolution and kill the 0!"
image="https://www.astro-shiba.com/astroshibalogo.ico"
status="live"
