VERSION="2.2.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCYV5ZMRG32T6FCY4S3K636XFQSGKLKREWONR7UUGOBTJZG72BPXSEF5",
"GD53LHKFAKRWD5JKJJLPSYU6ARIHQYEOSH4UHHGONGDIBIY6QEFJTZWO"]

[DOCUMENTATION]
ORG_NAME="Astro Shiba Inu"
ORG_URL="https://www.astro-shiba.com/"
ORG_TWITTER="astroshibainu"



[[CURRENCIES]]
code="ASHIB"
issuer="GD53LHKFAKRWD5JKJJLPSYU6ARIHQYEOSH4UHHGONGDIBIY6QEFJTZWO"
display_decimals=7
name="Astro Shiba"
desc="Astro Shiba token on Stellar Network"
image="https://www.astro-shiba.com/astroshibalogo.ico"
number=10000000000
status="live"
